server:
  port: 8484
spring:
  application:
    name: credit-card-verify-service
  pulsar:
    client:
      service-url: pulsar://localhost:6650
    producer:
      topic-name1: credit-card-apply
      topic-name2: credit-card-verify
    consumer:
      subscription:
        name: credit-card
    defaults:
      type-mappings:
        - messageType: com.example.event.VerifyCreditCardEvent
          schema-info:
            schema-type: JSON
        - messageType: com.example.event.NewCreditCardEvent
          schema-info:
            schema-type: JSON
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:credit-card-verify-application
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update